language: node_js
node_js:
  - "6"
install: 
  - npm install
script:
  - npm run build
  - npm run test
deploy:
  provider: npm
  api_key: NPM_API_KEY
  email: "koen.van.geert@gmail.com"
  on:
    tags: true